#!/usr/bin/env zsh
set -e

# --- Paths ---

PROJECT_DIR=$(cd "$(dirname "$0")"/.. && pwd)
PX4_DIR="${PROJECT_DIR}/deps/PX4-Autopilot"
WORLD_DIR="${PROJECT_DIR}/worlds"

# --- Gazebo paths ---
# export GZ_SIM_RESOURCE_PATH="${WORLD_DIR}:${GZ_SIM_RESOURCE_PATH}"
export GZ_SIM_RESOURCE_PATH="${WORLD_DIR}"
export GZ_SIM_MODEL_PATH="${WORLD_DIR}/models:${GZ_SIM_MODEL_PATH}"

# --- Tell PX4 which world to use ---
export PX4_GZ_WORLD="aruco2"

# --- Launch PX4 SITL (x500 drone) ---
make -C "${PX4_DIR}" px4_sitl gz_x500