<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_sim</name>
  <version>0.1.0</version>
  <maintainer email="mrmcmah@umich.edu">Mason McMahon</maintainer>
  <description>PX4 SITL simulation package for Gazebo and ROS 2 bridge.</description>
  <license>Apache-2.0</license>

  
  <!-- ROS2 dependencies -->
  <depend>rclpy</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>px4_msgs</depend>
  <depend>gazebo_ros</depend>

  <!-- Runtime -->
  <exec_depend>micrortps_agent</exec_depend>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
<export>
    <build_type>ament_python</build_type>
  </export>
</package>
